### ISSUE TITLE
Linker overlapping errors when adding sections to linker script

### ISSUE THREAD

**Issue by roel0** [japaric/embedded-in-rust#5]
I get the following linker issues when I add sections to the linker script:
(I used the linker script successfully in a C project)
```
>   = note: rust-lld: error: section .vector_table file range overlaps with .text
>           >>> .vector_table range is [0x1000, 0x10BF]
>           >>> .text range is [0x1000, 0x6D07]
>           
>           rust-lld: error: section .text file range overlaps with .debug_str
>           >>> .text range is [0x1000, 0x6D07]
>           >>> .debug_str range is [0x2000, 0x36DE7]
>           
>           rust-lld: error: section .text virtual address range overlaps with .vector_table
>           >>> .text range is [0x8000000, 0x8005D07]
>           >>> .vector_table range is [0x8000000, 0x80000BF]
>           
>           rust-lld: error: section .text load address range overlaps with .vector_table
>           >>> .text range is [0x8000000, 0x8005D07]
>           >>> .vector_table range is [0x8000000, 0x80000BF]
```

Linker script:
```
MEMORY {
  FLASH (rx) : ORIGIN = 0x08000000, LENGTH = 64K
  RAM (xrw) : ORIGIN = 0x20000000, LENGTH = 8K
}
SECTIONS
{
 .text : {
     *(.vectors)                                                                             
     *(.text*)
     . = ALIGN(4);
     *(.rodata*)
     . = ALIGN(4);
 } >FLASH
}
```
Application source (blink)
```
extern crate cortex_m_semihosting as sh;
extern crate panic_semihosting;
extern crate stm32l0;
extern crate cortex_m;
use stm32l0::stm32l0x3;

use core::fmt::Write;

use rt::ExceptionFrame;
use sh::hio;
use cortex_m::asm;

entry!(main);

fn main() -> ! {
    let mut stdout = hio::hstdout().unwrap();
    writeln!(stdout, "REL STINKT!").unwrap();
    let per = stm32l0x3::Peripherals::take().unwrap();
    let gpioa = &per.GPIOA;
    let rcc = &per.RCC;

    rcc.iopenr.write(|w| w.iopaen().set_bit());
    unsafe {
        gpioa.moder.write(|w| w.mode5().bits(1));
    }
    loop {
        gpioa.odr.write(|w| {
            w.od5().bit(gpioa.odr.read().od5().bit_is_clear())
        });
        for i in 0..1000 {
            asm::nop()
        }
    }
}

exception!(HardFault, hard_fault);

fn hard_fault(ef: &ExceptionFrame) -> ! {
    panic!("HardFault at {:#?}", ef);
}

exception!(*, default_handler);

fn default_handler(irqn: i16) {
    panic!("Unhandled exception (IRQn = {})", irqn);
}
```
Environment:

> o  blink cargo -V
> cargo 1.30.0-nightly (2fb77a49b 2018-09-07)
> o  blink rustup -V
> rustup 1.13.0
> o  blink cat Cargo.toml
> [package]
> name = "cortex-m-blink"
> version = "0.3.4"
> authors = ["roel0"]
> description = "a simple blink app"
> keywords = ["arm", "cortex-m", "template"]
> categories = ["embedded", "no-std"]
> 
> [profile.release]
> lto = true
> codegen-units = 1
> debug = false
> 
> [dependencies.cortex-m]
> version = "0.5.6"
> 
> [dependencies.cortex-m-rt]
> version = "0.5.3"
> 
> [dependencies.cortex-m-semihosting]
> version = "0.3.1"
> 
> [dependencies.panic-semihosting]
> version = "0.3.0"
> 
> [dependencies.stm32l0]
> version = "0.2.3"
> features = ["stm32l0x3", "rt"]
>

**Comment by japaric** [comment]
This kind of linker script will collide with the one provided by `cortex-m-rt`. If you would like to see support for adding custom sections please open an issue in the cortex-m-rt repository.

For information about writing your own linker script from scratch check out the [embedonomicon](https://rust-embedded.github.io/embedonomicon/).

This is the repository for my blog so I won't answer / discuss this kind of questions here.
